### PR TITLE
add votes stats page

### PR DESCRIPTION
**Pull request by dmnk89**

### CODE REVIEW

**Comment by margielm** [comment]
wonderful! 
I am just wondering if we need separate page to show it - or maybe we could incorporate that into existing presentation list. Both have pros and cons... so maybe we should add it in both places 🥁

**Comment by dmnk89** [comment]
I am not sure how fast the calculations of statistics will be (it fetches all votes and makes map-reduce).
I don't want to slow down different view just to display a table :)

but if it will be fast enought we can just add the component there... so lets see how it works :)

or do you suggest to add stats per presentation for each on /presentations page?

**Comment by margielm** [comment]
yup, the latter option.
just to display values next to each presentation. The drawback would be - that we will not have sorting for free. but the advantage - that all information will be in one place.
And of course this info would be visible only for the admin.
Btw. does it make sense that we write in english ?:)

**Comment by margielm** [comment]
ok, I dont have a problem with that :)

**Pull request merged**
